name: lint-action

on:
  pull_request:
    branches: ['main', 'develop']

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: BCSDLab/.github/.github/actions/setup-node@v1
        with:
          cache: 'pnpm'
      - name: Install Package
        run: pnpm install
      - name: Check lint
        run: pnpm lint
